title: "AliMo's Study Notes"
author: "Ali Mohamed"
description: "AliMo's Study Notes"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "ali.pdf", title: "My CV", icon: home}
  - {title: "About Me", file: "/about.md"}
  - {title: "Blog", file: "/blog.md"}
  - {title: "Contact Me", file: "/contact.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:alab@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/alimo9"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/aliabmo"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
